categories:
  camino: ~
  camino.darkMode:
    parent: camino
  camino.darkLightToggle:
    parent: camino

settings:
  camino.colorScheme:
    default: theme-caramel-cream
    type: string
    enum:
      - theme-caramel-cream
      - theme-ocean-breeze
      - theme-forest-mist
      - theme-violet-velvet
    category: camino
  camino.header.fixedPosition:
    default: false
    type: bool
    category: camino
  camino.darkMode.headerFooterContentColor:
    default: 'white'
    type: string
    enum:
      - white
      - black
    category: camino.darkMode
  camino.darkMode.colorPriority:
    default: 'dark-medium'
    type: string
    enum:
      - dark-medium
      - medium-dark
    category: camino.darkMode
  camino.darkLightToggle.type:
    default: ''
    type: string
    enum:
      - __none__
      - OneButtonTwoOptions
      - OneButtonThreeOptions
      - TwoButtons
      - ThreeButtons
    category: camino.darkLightToggle
  camino.darkLightToggle.iconType:
    default: UTF8
    type: string
    enum:
      - UTF8
      - SVG
    category: camino.darkLightToggle
  camino.darkLightToggle.position:
    default: 'right'
    type: string
    enum:
      - left
      - right
    category: camino.darkLightToggle
